instant:
    resource: "@InstantBundle/Resources/config/routing.yml"
    prefix:   /
user:
    resource: "@UserBundle/Resources/config/routing.yml"
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"