user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

instant:
    resource: "@InstantBundle/Resources/config/routing.yml"
    prefix:   /


